language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install autoconf automake autotools-dev libtool pkg-config
  - sudo apt-get -qq install libssl-dev ruby
before_script:
  - echo '-------------------------------'
  - echo 'Prepare mruby                  '
  - echo '-------------------------------'
  - git clone --depth 1 https://github.com/mruby/mruby.git
script:
  - echo '-------------------------------'
  - echo 'Build mruby-k2hash             '
  - echo '-------------------------------'
  - autoreconf -if
  - ./configure --with-mruby-prefix=./mruby
  - cd k2hash/fullock/ && ./autogen.sh && ./configure && make && sudo make install && cd ../../
  - cd k2hash/ && ./autogen.sh && ./configure && sudo make install && cd ../
  - sudo ldconfig
  - make
  - echo '-------------------------------'
  - echo 'Run unit test                  '
  - echo '-------------------------------'
  - mkdir -p mruby/build/host/mrbgems/
  - ln -s $TRAVIS_BUILD_DIR/ $TRAVIS_BUILD_DIR/mruby/build/host/mrbgems/mruby-k2hash
  - cp travis_config.rb mruby/
  - cd mruby/ && MRUBY_CONFIG=travis_config.rb ./minirake && cd ../
  - ./mruby/bin/mruby test/mruby-k2hash_test.rb
